import type { Anomaly, Ingestion, User, RiskHeatmapData } from './types';

export const mockAnomalies: Anomaly[] = [
  {
    id: 'ANOM-001',
    type: 'Duplicate Payment',
    description:
      'Potential duplicate payment detected for invoice INV-2023-987 to vendor "Innovate Inc."',
    date: '2023-10-26',
    status: 'AI Flagged',
    riskScore: 85,
    entity: 'Innovate Inc.',
    details: {
      transactionId: 'TXN-55432',
      amount: 15000,
      vendor: 'Innovate Inc.',
      violatedPatterns: ['Same invoice number, same amount, different transaction ID'],
      supportingEvidence: ['Payment Record A', 'Payment Record B'],
      transformationLogs: ['log_file_20231026.txt'],
      sourceDocuments: ['INV-2023-987.pdf'],
      complianceReference: 'Internal Control Policy 7.2: Duplicate Payment Prevention',
    },
  },
  {
    id: 'ANOM-002',
    type: 'Weekend Posting',
    description: 'Journal entry posted on a Saturday outside of business hours.',
    date: '2023-10-25',
    status: 'AI Flagged',
    riskScore: 45,
    entity: 'Internal JE',
    details: {
      transactionId: 'JE-00123',
      amount: 5230.75,
      violatedPatterns: ['Transaction posted on non-business day'],
      supportingEvidence: ['Journal Entry Log'],
      transformationLogs: ['log_file_20231025.txt'],
      sourceDocuments: ['JE-00123_details.pdf'],
      complianceReference: 'Company Policy 4.1: Standard Working Hours',
    },
  },
  {
    id: 'ANOM-003',
    type: 'Threshold Breach',
    description:
      'Payment of $250,000 to "Global Supply Co" exceeds the single payment threshold of $200,000.',
    date: '2023-10-24',
    status: 'AI Flagged',
    riskScore: 95,
    entity: 'Global Supply Co',
    details: {
      transactionId: 'TXN-55433',
      amount: 250000,
      vendor: 'Global Supply Co',
      violatedPatterns: ['Payment amount > $200,000'],
      supportingEvidence: ['Payment Authorization Form', 'Transaction Record'],
      transformationLogs: ['log_file_20231024.txt'],
      sourceDocuments: ['PO-456.pdf'],
      complianceReference: 'Delegation of Authority Matrix: L2 Approval required',
    },
  },
  {
    id: 'ANOM-004',
    type: 'Vendor Concentration',
    description:
      'Over 80% of Q4 marketing spend has been allocated to a single vendor "AdVantage LLC".',
    date: '2023-10-22',
    status: 'AI Flagged',
    riskScore: 60,
    entity: 'AdVantage LLC',
    details: {
      vendor: 'AdVantage LLC',
      violatedPatterns: ['Single vendor accounts for > 70% of category spend in a quarter'],
      supportingEvidence: ['Q4 Spend Analysis Report'],
      transformationLogs: ['log_file_20231022.txt'],
      sourceDocuments: ['Vendor_Spend_Q4.csv'],
      complianceReference: 'Procurement Policy 3.5: Vendor Diversification',
    },
  },
  {
    id: 'ANOM-005',
    type: 'Round Number',
    description:
      'A large, round-number payment of exactly $100,000.00 was made to "Consulting Experts".',
    date: '2023-10-20',
    status: 'AI Flagged',
    riskScore: 70,
    entity: 'Consulting Experts',
    details: {
      transactionId: 'TXN-55435',
      amount: 100000,
      vendor: 'Consulting Experts',
      violatedPatterns: ['Large payment with round number'],
      supportingEvidence: ['Transaction Record'],
      transformationLogs: ['log_file_20231020.txt'],
      sourceDocuments: ['SOW-CE-101.pdf'],
      complianceReference: 'Income Tax Act, 1961 - Section 40A(3): Cash Payment Limits',
    },
  },
];

export const mockIngestions: Ingestion[] = [
  {
    id: 'ING-001',
    source: 'SAP S/4HANA',
    type: 'API',
    date: '2023-11-01 02:00',
    status: 'Completed',
    recordCount: 150234,
    hash: 'a1b2c3d4...',
  },
  {
    id: 'ING-002',
    source: 'Q3_Invoices.zip',
    type: 'File',
    fileName: 'Q3_Invoices.zip',
    date: '2023-11-01 01:30',
    status: 'Completed',
    recordCount: 876,
    hash: 'b2c3d4e5...',
  },
  {
    id: 'ING-003',
    source: 'Amex Statements',
    type: 'SFTP',
    fileName: 'amex_202310.csv',
    date: '2023-11-01 00:00',
    status: 'Completed',
    recordCount: 5421,
    hash: 'c3d4e5f6...',
  },
  {
    id: 'ING-004',
    source: 'Oracle NetSuite',
    type: 'API',
    date: '2023-10-31 23:00',
    status: 'Processing',
    recordCount: 120000,
    hash: 'd4e5f6g7...',
  },
  {
    id: 'ING-005',
    source: 'Contracts_New.pdf',
    type: 'File',
    fileName: 'Contracts_New.pdf',
    date: '2023-10-31 18:00',
    status: 'Failed',
    recordCount: 0,
    hash: 'e5f6g7h8...',
  },
];

export const mockCurrentUser: User = {
  id: 'user-01',
  name: 'Alex Chen',
  email: 'alex.chen@auditai.com',
  avatarUrl: 'https://i.pravatar.cc/150?u=alexchen',
};

export const mockRiskHeatmapData: RiskHeatmapData = [
  { process: 'Procure to Pay', risk: 'High', value: 5 },
  { process: 'Procure to Pay', risk: 'Medium', value: 12 },
  { process: 'Procure to Pay', risk: 'Low', value: 45 },
  { process: 'Order to Cash', risk: 'High', value: 2 },
  { process: 'Order to Cash', risk: 'Medium', value: 8 },
  { process: 'Order to Cash', risk: 'Low', value: 60 },
  { process: 'Record to Report', risk: 'High', value: 8 },
  { process: 'Record to Report', risk: 'Medium', value: 15 },
  { process: 'Record to Report', risk: 'Low', value: 30 },
  { process: 'Payroll', risk: 'High', value: 1 },
  { process: 'Payroll', risk: 'Medium', value: 4 },
  { process: 'Payroll', risk: 'Low', value: 25 },
  { process: 'Treasury', risk: 'High', value: 3 },
  { process: 'Treasury', risk: 'Medium', value: 5 },
  { process: 'Treasury', risk: 'Low', value: 18 },
];
